battlecode/galaxy

frontend/src/views/multi-episode.jsx

Remember how we decided to use bc23 instead of 2023 as episode names? Forgot to port it everywhere
yay

Fix episode-dict keys to match (new) short names

---

frontend/src/views/login.js
frontend/src/views/passwordChange.jsx
frontend/src/views/passwordForgot.jsx
frontend/src/views/register.js

Things used to look like:
Now the div fits on the screen (including auto resizing!)
tests fine on Chrome with responsive device settings, although I'd like to verify on a proper mobile device sometime

Make divs on supporting pages responsive, so that they fit and work on small screens

---

backend/siarnaq/api/episodes/signals.py

```
POST  415  900 B  95 ms  Google-Cloud-Scheduler  https://api.battlecode.org/api/episode/e/bc23/autoscrim/
```
Looks like the default content-type is some nonsense. Let's specify it explicitly.

Fix autoscrim request content type

---

deploy/galaxy/main.tf
frontend/src/footer.js
frontend/src/index.js
frontend/src/navbar.js
frontend/src/sidebar.js
frontend/src/views/getting-started.js
frontend/src/views/issues.js
frontend/src/views/resources.js

In case a cache (at some level of caching) asks for them.
In particular, consider the Cloud CDN serving an old (cached) HTML file that has a link to an old, now-purged js file. But the js file was never cached. Things go south.
Also removes the "add trailing slash", cuz it turns out that adding trailing slash was a workaround and bandaid, but not a fix for the underlying problem.

Don't remove old files from frontend bucket

---

.github/ISSUE_TEMPLATE/bug-report-or-feature-request.md

closes #119 
**idea: when merged, what if we put the new link issue in the bug report channel, and either pin it (and change the channel description to make ppl see the pins) or put it smack in description?**

Add a generic issue template

---

frontend/src/components/paginationControl.js

Weird that jsut using `disabled` on the pagination buttons wasn't enough, must be due to the way the onClick is written. Either way, it's fixed now :+1:
Closes #382

Fix Rankings Pagination Bug

---

backend/siarnaq/settings.py

It needs to be structured json logs, not console-formatted stuff that isn't ingestable.

Make staging logging parseable

---

backend/siarnaq/api/compete/managers.py
backend/siarnaq/api/compete/models.py
deploy/saturn/main.tf
saturn/pkg/run/java8.go
saturn/pkg/run/protocol.go
saturn/pkg/run/recipe.go
saturn/pkg/run/scaffold.go
saturn/pkg/saturn/report.go
saturn/pkg/saturn/task.go

Essentially resolves todo list from #450; see below:
- Actually run the set of requested maps, instead of just maptestsmall.
- Grant permissions for logs to actually get written.
- Make logs more beautiful. Resolved siarnaq-side logging race condition by eliminating those log lines.
Other tasks completed:
- Instance pre-emption is handled very gracefully.
Remaining tasks to do:
- Investigate machine sizing vs runtime tradeoff.

Saturn enhancements

---

backend/siarnaq/api/compete/serializers.py

Closes #476, I think.
Issue hypothesis: `self.instance` has pre-fetched all the match participants, so the bulk update doesn't propagate through. Therefore it's trying to add up a bunch of NoneTypes when calculating ratings.

Fix nonetype on match score

---

frontend/src/components/rankingTeamList.js
frontend/src/components/scrimmageRequestForm.js

- Teams without an active submission: remove them entirely from the list.
- Disallow ranked matches against staff. It's enforced by backend, so let's enforce on frontend too. As a side-effect, matches now default to unranked.
- Show team quote (useful because Dev team contains message about "we're running examplefuncs!")

Small changes to scrimmage request team search

---

frontend/src/sidebar.js

Removes a TODO that I considered, but on second thought it's fine. It's a simple duped thing, and only occurs twice. More importantly, that de-dupe is actually nontrivial (cuz the parts get used elsewhere). And the code is simple enough now thanks to auxiliary changes.
For security bugs / permission checks: carefully went through, and couldn't find anything. Also people haven't broken prod yet, which is good!!
I think we can release now, and let people file bugs as necessary. But our own internal QA is probably good (at least with regards to this issue)

Address #74

---

saturn/pkg/saturn/report.go

http -> https redirect causes subsequent requests to be incorrectly issued as GET

Follow redirects on POST requests

---

frontend/src/api.js
frontend/src/components/submissionList.js
frontend/src/index.js
frontend/src/views/submissions.js

Closes #78. Also closes #33 by making it moot.

Show tournament submissions in frontend

---

backend/siarnaq/api/compete/signals.py
backend/siarnaq/api/compete/test_views.py

As discussed here's the quick braindead fix for now (cuz time press). 
UI/UX is probably now weird. Should announce in discord (and make frontend more intuitive later, like in Maggie's PR?)

Disable auto-accept for ranked scrimmages (and do nothing else)

---

deploy/releases/main.tf

Release agent, for some reason, needs the `storage.buckets.get` permission.

Hotfix release permissions

---

saturn/pkg/run/java8.go

**Hold deploy pending actual map fixes, just for cleanliness/sanity**
Reverts battlecode/galaxy#532
Turns out, there's major cost in not running map validation -- sometimes we forget to validate on our own! This leads to rough tournaments.
(And the time/money saved by skipping this step is marginal and not worth)

Revert "Do not run map validation"

---

backend/siarnaq/api/episodes/admin.py

To not interleave tournaments when they have the same submission freeze time (and same other keys really)

Sort tournamentRounds by tournament name

---

.github/workflows/ci.yml
frontend2/.eslintrc.js
frontend2/src/components/EpisodeLayout.tsx
frontend2/src/components/sidebar/SidebarItem.tsx
frontend2/src/components/sidebar/SidebarSection.tsx
frontend2/src/components/sidebar/__test__/Sidebar.test.tsx
frontend2/src/components/sidebar/index.tsx
frontend2/src/index.tsx

makes frontend2 tests / linting run on each pr.

Add frontend lint / tests to ci workflow

---

frontend2/.eslintrc.js
frontend2/.prettierignore
frontend2/src/components/BattlecodeTable.tsx
frontend2/src/components/elements/Button.tsx
frontend2/src/utils/api.ts
frontend2/src/utils/auth.ts
frontend2/src/views/Rankings.tsx

- Changed API/Auth to be exported functions in separate files.
- Accidentally changed ~5000 lines by running format (oopsie).
:rocket:

Api Cleanup

---

frontend2/src/components/elements/Tooltip.tsx

example usage:
```
<Tooltip text="this is part of the tooltip.">
<p className="text-pink-500">the default location for a tooltip is top</p>
</Tooltip>
<Tooltip location="right" text="This is an incredibly long tooltip text that should wrap nicely">
<Icon name="arrow_up_tray" size="sm" />
</Tooltip>
<Tooltip location="left" text="This is an incredibly long tooltip text that should wrap nicely">
<Icon name="map" size="sm" />
</Tooltip>
<Tooltip location="bottom" text="short tooltip">
<Icon name="map" size="sm" />
</Tooltip>
```

Add tooltip

---

frontend2/src/App.tsx
frontend2/src/components/CurrentUserProvider.tsx
frontend2/src/components/EpisodeLayout.tsx
frontend2/src/components/Header.tsx
frontend2/src/components/compete/RatingDelta.tsx
frontend2/src/components/sidebar/__test__/Sidebar.test.tsx
frontend2/src/components/sidebar/index.tsx
frontend2/src/contexts/CurrentTeamContext.ts
frontend2/src/contexts/CurrentTeamProvider.tsx
frontend2/src/contexts/EpisodeContext.ts
frontend2/src/contexts/EpisodeProvider.tsx
frontend2/src/utils/api/team.ts
frontend2/src/views/Account.tsx
frontend2/src/views/Login.tsx
frontend2/src/views/Queue.tsx
frontend2/src/views/Rankings.tsx
frontend2/src/views/Register.tsx

Adds a context to store the user's current team's information.
Updates the user context to reduce rerendering
Updates Episode context to contain full episode information instead of just the id, and adds EpisodeProvider, which encapsulates the logic for loading the full episode information.
- Note that there are two hooks to get episode data: `useEpisode` and `useEpisodeId`. `useEpisode` contains full episode data, and `useEpisodeId` contains the episodeId and a fucntion to set the episode id. I set it up this way to avoid rerenders.
- components that only require episodeId will not rerender when the full episode data is loaded. ( I documented this in the code as well)

Add team context, update user/episode context

---

frontend2/src/components/sidebar/__test__/Sidebar.test.tsx
frontend2/src/components/sidebar/index.tsx

If the user is not logged in, the entire TEAM MANAGEMENT section of the sidebar should not appear
If the user is logged in and does not have a team, the Submissions and Scrimmaging sections should not appear
If the user is logged in and has a team, the entire TEAM MANAGEMENT section should appear

Add team sidebar display conditions

---

frontend2/src/App.tsx
frontend2/src/components/Header.tsx
frontend2/src/components/JoinTeam.tsx
frontend2/src/components/SectionCard.tsx
frontend2/src/components/elements/DescriptiveCheckbox.tsx
frontend2/src/components/elements/FormLabel.tsx
frontend2/src/components/elements/SelectMenu.tsx
frontend2/src/components/elements/TextArea.tsx
frontend2/src/components/team/MemberList.tsx
frontend2/src/contexts/CurrentTeamContext.ts
frontend2/src/contexts/CurrentTeamProvider.tsx
frontend2/src/index.css
frontend2/src/views/MyTeam.tsx

Adds the team settings page. This PR doesn't add any functionality - only the design.
TODO:

Add the my team settings page

---

frontend/src/views/multi-episode.jsx
frontend/src/views/resources.js
frontend/src/views/tournaments.js

Updates our frontend to battlecode 2024!
* Check that going to play.battlecode.org redirects to bc24 home
* Check that creating a team creates a bc24 team
* Check that you can join a bc24 team
* Check all the pages to ensure nothing is broken

Change default episode to bc24

---

frontend2/src/components/sidebar/__test__/Sidebar.test.tsx
frontend2/src/contexts/CurrentTeamContext.ts
frontend2/src/contexts/CurrentTeamProvider.tsx
frontend2/src/utils/api/team.ts

Add refreshTeam() to team context to enable updates of team state (needed for the Create/Join Team and My Team pages)
Add updateTeamPartial() api call (needed for My Team page)
will unblock @sri240 for create/join team

add updateteampartial api call, add refreshTeam to team context

---

frontend2/src/components/Loading.tsx
frontend2/src/components/PrivateRoute.tsx
frontend2/src/components/Spinner.tsx
frontend2/src/components/Table.tsx
frontend2/src/components/elements/DescriptiveCheckbox.tsx
frontend2/src/components/team/EligibilitySettings.tsx
frontend2/src/components/team/ScrimmageSettings.tsx
frontend2/src/views/MyTeam.tsx

Make the big checkboxes for changing eligibility / scrim settings work.
When reviewing / testing, please especially watch out for race conditions. I think I've addressed all potential race conditions, but would appreciate another check.
Testing plan:
* Be on a team. Click a checkbox. The spinner should appear in the checkbox until the request is resolved, and the checkbox should be set to the opposite of what it was before. 
* The checkbox should not be clickable while it is in the loading state.
* Clicking multiple checkboxes fast should not lead to inconsistent behavior
Merge after https://github.com/battlecode/galaxy/pull/699
Example:

Support changing eligibility and scrim settings

---

backend/siarnaq/api/compete/serializers.py
backend/siarnaq/api/compete/test_views.py
backend/siarnaq/api/compete/views.py

Enables lookup of tournament matches by external id. Needed for client tourney display
Updates/adds tests to cover external id query param for /tournament in matchviewset
API endpoint:  `api.battlecode.org/api/compete/bc23/match/tournament/`
Example parameters for client:
`http://localhost:8000/api/compete/bc23/match/tournament/?external_id_private=privatechallongid`
Example response
```json
{
"count": 21,
"next": "http://localhost:8000/api/compete/bc23/match/tournament/?external_id_private=<private id here>&page=2&tournament_id=bc23tt29",
"previous": null,
"results": [
{
"id": 203,
"status": "OK!",
"episode": "bc23",
"tournament_round": {
"id": 262,
"tournament": "bc23tt28",
"external_id": 6,
"name": "Round 6 (Winners)",
"maps": [
3
],
"release_status": 2
},
"participants": [
{
"team": …
```

enable tourney match lookup by external id 

---

backend/siarnaq/api/compete/test_views.py
backend/siarnaq/api/episodes/serializers.py

`display_order` specifies what order to display the `TournamentRounds` of a `Tournament`
Test plan
* ensure display_order is in the response of tournament round endpoints

expose tournament round display order field

---

backend/siarnaq/api/compete/views.py

fixes 404 on scrimmaging page by moving check for # of tournaments = 1, which was a bug added in the external id private lookup pr

fix 404 on scrimmaging page

---

backend/siarnaq/api/teams/views.py

Fixes a bug in the team report endpoints where we didn't filter for episode
Tested locally with a user on 2 teams. `GET /api/team/{episode_id}/requirement/report/` returned 404 which is expected (previously returned 500)

fix multiepisode strategy report bug

---

deploy/.terraform.lock.hcl
deploy/galaxy/main.tf
deploy/main.tf

change execute machines from `t2d-standard-4` to `t2d-standard-16`
increase execute parallelism from 2 to 12 (run 12 games / machine instead of 2 games/machine)
decrease max number of execute instances from 50 to 10
increase load ratio to 50 (50 games in queue / machine)
reasoning (jerry)
* scale up delay is less heinous
* scale down is less likely to kill a half-complete game
* you can get away with allocating less memory per game because most games are low-memory, and worst-case games aren’t frequent

change execute machines to t2d-standard-16

---

saturn/pkg/saturn/task.go

If an error occurs while running a task, log a traceback.
This PR also fixes the bug where the error from running a task was overriden/deleted by the error from calling FinalizeReport, resulting in our logs not containing the error.
**Testing**: not sure how to test this locally

log tracebacks for tasks, log errors properly

---

frontend2/src/App.tsx
frontend2/src/components/EpisodeSwitcher.tsx
frontend2/src/views/EpisodeNotFound.tsx
frontend2/src/views/Login.tsx
frontend2/src/views/NotFound.tsx
frontend2/src/views/PageNotFound.tsx

Fixes some routing insecurities and improves flow of control around episode switching.
Closes #794 :rocket:

Routing Improvements

---

frontend2/.env.development
frontend2/public/index.html
frontend2/src/App.tsx
frontend2/src/api/loaders/teamProfileLoader.ts
frontend2/src/components/sidebar/index.tsx
frontend2/src/components/tables/RankingsTable.tsx
frontend2/src/components/team/MemberList.tsx
frontend2/src/views/TeamProfile.tsx

Team Profile page (for other teams)

---

frontend2/package-lock.json
frontend2/package.json
frontend2/src/App.tsx
frontend2/src/components/OptionalSectionCardMarkdown.tsx
frontend2/src/components/sidebar/index.tsx
frontend2/src/content/ContentStruct.ts
frontend2/src/content/ManageContent.ts
frontend2/src/content/bc22.ts
frontend2/src/content/bc23.ts
frontend2/src/content/bc24.ts
frontend2/src/views/CommonIssues.tsx
frontend2/src/views/DebuggingTips.tsx
frontend2/src/views/NoContentLegacyEpisode.tsx
frontend2/src/views/QuickStart.tsx
frontend2/src/views/Resources.tsx
frontend2/src/views/Tournaments.tsx

Modified src/content folder to add a content file for each episode
created ManageContent.ts to create records: <episode_id, text> for each content page: quickstart, resources and tournaments
created ContentStrucuts.ts to manage types used in Tournament record
Closes #785 :rocket:

loading content for each episode

---

frontend2/src/App.tsx
frontend2/src/api/helpers.ts
frontend2/src/api/loaders/episodeLoader.ts
frontend2/src/api/loaders/homeIfLoggedIn.ts
frontend2/src/api/loaders/homeLoader.ts
frontend2/src/api/loaders/myTeamLoader.ts
frontend2/src/api/loaders/queueLoader.ts
frontend2/src/api/loaders/rankingsLoader.ts
frontend2/src/api/loaders/scrimmagingLoader.ts
frontend2/src/api/loaders/submissionsLoader.ts
frontend2/src/api/loaders/teamProfileLoader.ts
frontend2/src/api/loaders/tournamentLoader.ts
frontend2/src/api/loaders/tournamentsLoader.ts

This fixes the issue of loaders throwing runtime errors. I added a few notes, feel free to give your thoughts on them. tyty

Safe Loaders

---

frontend2/src/api/auth/authApi.ts
frontend2/src/api/loaders/homeIfLoggedIn.ts
frontend2/src/components/Header.tsx
frontend2/src/components/PrivateRoute.tsx
frontend2/src/components/elements/Button.tsx
frontend2/src/components/elements/Icon.tsx
frontend2/src/components/elements/Input.tsx
frontend2/src/views/Login.tsx

- Fixes weird bugs caused by #837 (`homeIfLoggedIn`) where we had infinite navigate cycles (yippeeee).
- Also adds a button to the login page where you can toggle visibility of your password

Auth Routing

---

frontend2/src/views/ErrorBoundary.tsx

Prettier error-page

---

frontend/src/components/Header.tsx
frontend/src/components/Table.tsx
frontend/src/components/TableBottom.tsx
frontend/src/components/compete/ScrimmagingRecord.tsx
frontend/src/components/compete/TeamWithRating.tsx
frontend/src/components/compete/TournamentCountdown.tsx
frontend/src/components/elements/Icon.tsx
frontend/src/components/tables/RankingsTable.tsx
frontend/src/components/tables/scrimmaging/TeamsTable.tsx
frontend/src/views/Queue.tsx
frontend/src/views/Rankings.tsx
frontend/src/views/Scrimmaging.tsx
frontend/src/views/Submissions.tsx

- makes mobile view sizes first-class on the dashboard
- major rework of our table scheme to enable mobile viewing (chefs kiss)
Resolves #870 :rocket:

Beautify mobile UI

---

frontend/src/components/Table.tsx
frontend/src/components/tables/RankingsTable.tsx
frontend/src/components/tables/TournamentsTable.tsx
frontend/src/components/tables/scrimmaging/TeamsTable.tsx

- reduces x axis padding on mobile table contents for extra space
- removes trimstring jank and use clever wrapping and ellipsis styling :)
- change some table value functions to behave better and not break the styling

Mobile Table Overflow

---

frontend/src/components/CountdownDisplay.tsx
frontend/src/components/EpisodeLayout.tsx
frontend/src/components/compete/TournamentCountdown.tsx
frontend/src/content/bc25java.ts
frontend/src/content/bc25python.ts

- updated prizes info
- tinkered with episode layout for better vertical gray background filler

Almost done prizes info

---

frontend/src/views/TeamProfile.tsx

Removes "Team Biography" section below "Biography" on team profile page. ("Biography" more consistent with rest of profile than "Team Biography")

Remove duplicated team biography on team profile view

---

backend/siarnaq/api/compete/admin.py
backend/siarnaq/api/compete/managers.py

- fixing the problem of ranked scrimmages rating being all 0s
- can re-calculate ratings again in admin interface 
- should recalc starting from oldest

admin recalc ratings

---

backend/siarnaq/api/compete/test_views.py
backend/siarnaq/api/episodes/serializers.py
backend/siarnaq/api/episodes/views.py
frontend/schema.yml
frontend/src/App.tsx
frontend/src/api/_autogen/apis/EpisodeApi.ts
frontend/src/api/_autogen/models/TournamentRound.ts
frontend/src/api/episode/episodeApi.ts
frontend/src/api/episode/episodeFactories.ts
frontend/src/api/episode/episodeKeys.ts
frontend/src/api/episode/useEpisode.ts
frontend/src/api/helpers.ts
frontend/src/api/loaders/adminTournamentLoader.ts
frontend/src/components/elements/Icon.tsx
frontend/src/components/elements/SelectMultipleMenu.tsx
frontend/src/components/tables/TournamentsTable.tsx
frontend/src/views/AdminTournament.tsx
frontend/src/views/Scrimmaging.tsx

this is like halfway done? things that are sus rn:
- when exactly can we create/enqueue?
- TODO actually refetch rounds on c/e success :)
- TODO better error messages when things fail
- active round is... the earliest round that is "in progress"
- we can rerun the round once all matches are completed only if the next round isnt in progress. this should rerun all the matches using match "requeue" functionality (need a new api request on tournament round which forcibly requeues all its matches)
- you can only start a round once the previous round's matches are all successful/completed
- 
- when can we release? what exactly does releasing do?
- we dont release until the next day (until stream)
- as the rounds are shown we release them
- rounds can be released once all their matches are …

Tournament admin page

---

backend/siarnaq/api/compete/serializers.py

- hide result info for unreleased tournament matches
doing it this way for now bc my staging is sooooo broken and i want to fix this asap

emergency hide match results

---

backend/README.md
backend/siarnaq/bracket/challonge.py

]Attachments change: To actually _let_ us add attachments (in our case, replay links). Attaching via API doesn't work but at least you can do manually
Game name: This is required not by the API v2 but by the tournament settings _website_. (Either they do frontend validation or use v1 of API.) So if you ever change the settings manually via website, you have to go back and add the game name, which gets really painful.... Also all our other tournaments have game name anyways, so might as well keep that around.
Also includes some dev notes

Better options for creating challonge tournaments

---

backend/siarnaq/api/compete/serializers.py
backend/siarnaq/api/compete/test_views.py
backend/siarnaq/api/compete/views.py
backend/siarnaq/api/episodes/admin.py
backend/siarnaq/api/episodes/models.py
backend/siarnaq/api/episodes/serializers.py
backend/siarnaq/api/episodes/views.py
frontend/src/api/episode/useEpisode.ts
frontend/src/views/AdminTournament.tsx

- altogether hides tournament matches for unreleased rounds, unless the user is staff or the matches are requested with external id private
- adds link to django admin for private challonge bracket :)
- fixes tournament match maps ordering with a lovely hack fix :sob: 
- dont hide round maps if the user is staff
- better error display in frontend when things go wrong (but not for initialize bc that is an asynchronous task)
- actually list maps in admin page

Fixes for Tourney Admin
