battlecode/galaxy

frontend/src/views/home.js

Emphasize our communication channels / social media

---

frontend/src/footer.js
frontend/src/index.js
frontend/src/navbar.js
frontend/src/sidebar.js
frontend/src/views/getting-started.js
frontend/src/views/issues.js
frontend/src/views/resources.js
frontend/src/views/team.js

Index has copies of routes (w and w/o trailing slash) cuz we can expose many things

Fix team error display; attach trailing slashes

---

frontend/public/bc/css/bc_styles.css

Fix alert z-index

---

backend/Dockerfile

I am a potato and messed up #350.

Fix cmdline argument

---

backend/siarnaq/settings.py

I was a potato in #350 and #352.

Add SSL proxy header

---

backend/siarnaq/settings.py

limit a user from sending more than 100 api calls per minute
closes #331

implement throttling, limit api calls to 100 per minute

---

backend/siarnaq/api/compete/filters.py
backend/siarnaq/api/compete/managers.py
backend/siarnaq/api/compete/permissions.py
backend/siarnaq/api/compete/views.py
backend/siarnaq/api/episodes/permissions.py
backend/siarnaq/api/teams/views.py
backend/siarnaq/api/user/views.py

I think `self.action` is supposed to be set, but for some reason it's `None`. Let's just eliminate our reliance on it.
Closes #357.

Fix incorrect usage of self.action

---

backend/siarnaq/api/episodes/models.py
backend/siarnaq/api/episodes/serializers.py

Expose episode frozen status and do not freeze for private tournament

---

frontend/src/views/not_found.js

changed the variable name to more general and changed page not found icon

---

frontend/public/index.html
frontend/src/footer.js
frontend/src/index.js
frontend/src/navbar.js
frontend/src/views/getting-started.js
frontend/src/views/issues.js
frontend/src/views/login.js
frontend/src/views/multi-episode.jsx

both things are kinda intertwined, since our episodes are nested in routes
gonna make this a bit higher pri cuz it's just gonna keep needing rebases and that makes me sad
Fixes #381, and some other odd routing bugs

Add leading slashes where needed; Remove concept of episode from some pages

---

backend/Dockerfile
backend/siarnaq/settings.py
deploy/cd/main.tf
deploy/galaxy/main.tf
deploy/galaxy/variables.tf
deploy/main.tf
deploy/network/main.tf
deploy/network/outputs.tf
deploy/network/variables.tf
deploy/siarnaq/main.tf
deploy/siarnaq/outputs.tf
deploy/siarnaq/variables.tf

Initial version that is syntactically valid, but yet not attempted to deploy. Requesting review as a sanity-check before attempting to touch deployed resources.
Not yet implemented: adding Cloud IAP to control access to staging. For now, the environment will be publicly available over the internet (no security risk, just not desired). Suggesting to save this for a later PR.
Closes #324.

Add staging backend environment

---

backend/siarnaq/settings.py
deploy/siarnaq/main.tf

Correctly inject environment variable into build

---

backend/siarnaq/settings.py

This should fix #403 in the lazy way. If this resolves the issues, then we also don't have to worry about the causes anymore because we'll no longer have such a reliance on the IAM API.

Do not impersonate service accounts on GCE

---

frontend/src/views/getting-started.js
frontend/src/views/issues.js
frontend/src/views/resources.js
frontend/src/views/tournaments.js

Some of our discord links linked to channels, so people who weren't part of the server couldn't see the channel. I changed discord channel links to an invite link to the server.

change all discord links to the invite code

---

frontend/src/views/login.js
frontend/src/views/passwordForgot.jsx
frontend/src/views/register.js

from nathan: closes #24 and closes #409
I'm not even sure if you should _get_ credit for two issues when it's a dupe but, eh, enjoy it
See attached screenshots; this PR adds the links below the form submit buttons.

Link register, login, and password reset pages to each other

---

frontend/src/views/tournaments.js

updated resume requirement to exclude sprint tournaments, change sprint tournament 2 to sprint 2 tournament
closes #412

remove resume requirement from sprint, fix minor typo

---

frontend/src/views/submissions.js

Closes #425
Mainly:
- fixes a typo (episode_info not episode)
- Includes a staff override
- Improves docs

Properly check whether users can submit code

---

frontend/public/bc/css/bc_styles.css
frontend/src/api.js
frontend/src/components/alert.js
frontend/src/utils/error_handling.js
frontend/src/views/account.js
frontend/src/views/login.js
frontend/src/views/passwordChange.jsx
frontend/src/views/passwordForgot.jsx
frontend/src/views/register.js
frontend/src/views/submissions.js
frontend/src/views/team.js

Closes #315 and closes #338 and closes #423 and closes #421
That was a fun 3 hours
Better error handling in general. Feel free to test, See screenshots for examples

Show better errors in frontend

---

frontend/src/views/passwordChange.jsx
frontend/src/views/passwordForgot.jsx

Added loading indication for the password forget interface 

---

frontend/src/views/register.js

Note that this is on top of #424

Show request loading spinner when registering

---

frontend/src/views/team.js

To make it clear the update button applies to both. Note this on top of #424

Merge tournament eligibility and team update cards

---

frontend/src/components/rankingTeamList.js
frontend/src/index.js
frontend/src/views/submissions.js

Show info about freeze for submissions and scrimmage reqs

---

frontend/src/views/scrimmaging.js

Fix scrimmage history refresh

---

frontend/src/views/scrimmaging.js

Correct link to visualizer replays

---

frontend/src/components/submissionList.js

if and only if status="OK!":
then show "Accepted" or "Rejected" (based on the accepted var)
This solution works if the submission status is anything other than ok, I am not sure that it works if status is OK! because I don't know how to create a submission that is "OK!" to test it. I think the logic is right though.

show accept/reject on submissions

---

saturn/pkg/run/file.go
saturn/pkg/run/gcs.go
saturn/pkg/run/java8.go

Ensure replays are publicly downloadable

---

deploy/galaxy/main.tf
deploy/main.tf
deploy/saturn/main.tf

Update saturn parameters

---

saturn/pkg/run/java8.go

Flush build directory before run

---

frontend/src/index.js
frontend/src/views/getting-started.js
frontend/src/views/resources.js

Have frontend smoothly change itself upon game release via conditional rendering

---

frontend/public/bc/css/bc_styles.css
frontend/src/components/rankingTeamList.js

- Made rating and team name cells link to team page
- Team member names link to individual user pages
Closes #443 :rocket:

Improve Rankings Table Links

---

frontend/src/components/scrimmageRequestForm.js

Temporarily disable requesting shuffled color

---

frontend/src/components/rankingTeamList.js

Makes word wrap happen and rows not explode.

Add a space

---

frontend/src/views/tournaments.js

us quals: entirely us college students
intl quals: entirely intl college students
hs tour: entirely hs students (us or intl)

update tournament eligibility

---

frontend/src/components/rankingTeamList.js

robust fix for later. See #506 and #504 for those...but for now...

Disable filtering for now

---

backend/siarnaq/api/compete/models.py
backend/siarnaq/api/episodes/signals.py
deploy/main.tf
deploy/network/main.tf
deploy/network/variables.tf
saturn/pkg/saturn/report.go

Closes #509 by reverting a bunch of code and making the infrastructure nicer instead.

Use https everywhere

---

backend/siarnaq/api/teams/filters.py
backend/siarnaq/api/teams/views.py
frontend/src/api.js
frontend/src/components/rankingTeamList.js
frontend/src/components/rankingTeamSearch.js
frontend/src/components/scrimmageRequestor.js
frontend/src/views/rankings.js

Closes #504. Unsure what this does to #506.

Properly implement filtering by active submission

---

backend/siarnaq/api/compete/permissions.py
backend/siarnaq/api/compete/test_views.py
backend/siarnaq/api/compete/views.py

Fix scrimmage requests crash

---

deploy/saturn/main.tf

Disable message ordering

---

backend/README.md
backend/docs/operations.md

Closes #522
yes you could debate about exact location, wording, etc. Would like to save that for later though. Just want to get _something_ up for rest of month

Add basic docs about email reset

---

frontend/src/components/countdown.js
frontend/src/components/submissionList.js
frontend/src/utils/date.js
frontend/src/views/queue.js
frontend/src/views/scrimmaging.js

Add timezone and localization everywhere I could find

---

frontend/src/views/queue.js
frontend/src/views/scrimmaging.js

remove N/A from queue and scrimage history

---

frontend/src/views/queue.js

i'm confident enough that i'll force push and hot fix, will stay to make sure it does resolve tho
fix #536

Fix queue page by importing floater

---

deploy/galaxy/main.tf
deploy/galaxy/variables.tf
deploy/main.tf
deploy/siarnaq/main.tf

More game runners. Less webserver resource.

Adjust deploy parameters

---

frontend/src/api.js
frontend/src/views/submissions.js

Error message now displays this (the 5 MiB is hardcoded though):

changed file size check to be on frontend

---

frontend/src/views/queue.js
frontend/src/views/scrimmaging.js

Fancy rating rendering

---

backend/siarnaq/middleware.py
backend/siarnaq/settings.py

Make timezones show in ET

---

backend/siarnaq/api/episodes/serializers.py
backend/siarnaq/api/teams/managers.py

Compute team eligibility

---

backend/siarnaq/api/episodes/admin.py
backend/siarnaq/api/user/admin.py

Closes #519. Addresses issue raised by #531.

Minor updates to admin page

---

backend/siarnaq/api/compete/models.py
frontend/src/components/scrimmageRequestForm.js
saturn/pkg/run/java8.go
saturn/pkg/run/protocol.go

In conjunction with battlecode/battlecode23#124 and battlecode/battlecode23-scaffold#4, closes #485.

Support alternating player order

---

backend/siarnaq/api/teams/signals.py

Fix deleting empty teams

---

deploy/galaxy/main.tf

Closes #568
TODO afterwards deploy!

Switch execute (game-runner) server to higher memory

---

frontend/src/utils/date.js

Hide seconds from time

---

frontend/src/api.js
frontend/src/index.js
frontend/src/views/queue.js
frontend/src/views/scrimmaging.js
frontend/src/views/tournaments.js

Closes #15. Have made #567 for future improvements.

Show list of tournament matches

---

deploy/cd/main.tf
deploy/cd/variables.tf
deploy/galaxy/main.tf
deploy/galaxy/variables.tf
deploy/main.tf
deploy/network/main.tf
deploy/network/variables.tf
deploy/releases/main.tf
deploy/releases/variables.tf
deploy/saturn/main.tf
deploy/saturn/variables.tf
deploy/siarnaq/main.tf
deploy/siarnaq/variables.tf
deploy/titan/main.tf
deploy/titan/variables.tf
deploy/variables.tf

Several terraform updates

---

backend/environment.yml
backend/siarnaq/api/compete/models.py
backend/siarnaq/api/compete/signals.py
backend/siarnaq/api/compete/test_models.py
backend/siarnaq/api/compete/views.py
backend/siarnaq/api/user/authentication.py
backend/siarnaq/gcloud/tasks.py
backend/siarnaq/settings.py
deploy/.terraform.lock.hcl
deploy/main.tf
deploy/provider.tf
deploy/siarnaq/main.tf
environment-dev.yml

Use Cloud Tasks for rating updates

---

backend/siarnaq/api/compete/serializers.py
backend/siarnaq/settings.py
frontend/package-lock.json
frontend/package.json
frontend/src/components/rankingTeamList.js
frontend/src/components/rankingTeamSearch.js
frontend/src/components/scrimmageRequestForm.js
frontend/src/components/scrimmageRequestor.js

Improvements to scrimmage requests

---

backend/siarnaq/api/compete/serializers.py
backend/siarnaq/api/compete/views.py
backend/siarnaq/api/teams/models.py

Historical Elo Endpoint

---

backend/siarnaq/api/compete/views.py
backend/siarnaq/api/episodes/views.py

Do not throttle admin methods

---

frontend/src/components/avatarUpload.js
frontend/src/views/account.js

frontend avatar and resume file size check

---

frontend/src/views/codeofconduct.js
frontend/src/views/home.js
frontend/src/views/tournaments.js

tourney seeding should be determined by scrimamge ranking, not sprint 2 tourney results
updated code of conduct a bit

update code of conduct, link to it on home, update tourney seeding

---

frontend/src/views/home.js

This fixes the issue that causes the website not to load in production at the moment.

Import NavLink on home view

---

backend/siarnaq/api/compete/signals.py

Force happens-before with match result and rating

---

backend/siarnaq/api/episodes/models.py
backend/siarnaq/api/teams/managers.py

annotations conflict :(( here is a hotfix. it is unperformant but it should suffice.
Real solution would use Subquery but I have little understanding right now...

Fix that computing eligibility and tournament entrants 

---

backend/siarnaq/api/teams/admin.py

Don't show inline submission and matchParticipant in team panel to save bloat

---

frontend/src/views/tournaments.js

haven't tested locally yet but it's just text changes so it should be fine

update tournament prize amounts

---

backend/siarnaq/api/episodes/admin.py
backend/siarnaq/api/user/managers.py
backend/siarnaq/gcloud/titan.py
backend/siarnaq/settings.py
deploy/galaxy/main.tf
deploy/siarnaq/main.tf
deploy/siarnaq/variables.tf

Support mass resume download

---

.vscode/settings.json
frontend2/.eslintrc.js
frontend2/package-lock.json
frontend2/package.json
frontend2/tailwind.config.js

* adds eslint rule for indents being 2 spaces
* fixes npm errors by using ts 4.9.5 instead of 5.0.4
* adds heroicons and headless ui packages

Fix npm errors and enforce spacing

---

backend/siarnaq/api/teams/serializers.py

Requesting that Jerry review this if possible because he most recently touched this code.
This PR fixes a bug that allows users to change what episode their team belongs to, and if their team has a report or not.
Testing:
* Tested creating and updating a team locally.

Fix team update/create bugs

---

frontend2/src/index.css
frontend2/src/utils/constants.ts
frontend2/src/views/Login.tsx
frontend2/src/views/Register.tsx

Adds the login page.
Testing:
* Try logging in with invalid username / pwd. Error message should appear
* Try logging in with correct username / pwd. Login should succeed and should redirect to the home page of the most recently accessed episode.
* Try going to the /login page while already logged in. It should redirect you to the home page of the most recently accessed episode.
Note: testing is blocked on https://github.com/battlecode/galaxy/pull/667.

Add login page

---

frontend2/src/components/elements/Collapse.tsx
frontend2/src/views/Home.tsx

```jsx
<Collapse title="This is the title">
<p>Some content here</p>
<div className="flex flex-row gap-2">
<Icon name="check" />
<p>alskdjfasdf</p>
<h1>asdfljkasldkfj</h1>
</div>
</Collapse>
```

Add Collapsible

---

frontend2/package.json
frontend2/src/App.tsx
frontend2/src/components/BattlecodeTable.tsx
frontend2/src/components/Loading.tsx
frontend2/src/components/elements/Markdown.tsx
frontend2/src/content/bc23.ts
frontend2/src/utils/api/episode.ts
frontend2/src/utils/dateTime.ts
frontend2/src/utils/loadTeams.ts
frontend2/src/views/Queue.tsx
frontend2/src/views/Tournament.tsx
frontend2/src/views/Tournaments.tsx

Adds the Tournaments and Tournament pages!

Tournaments Page

---

frontend2/src/components/Loading.tsx
frontend2/src/components/Modal.tsx
frontend2/src/components/PrivateRoute.tsx
frontend2/src/components/Spinner.tsx
frontend2/src/components/Table.tsx
frontend2/src/components/elements/AsyncSelectMenu.tsx
frontend2/src/components/elements/Button.tsx
frontend2/src/components/sidebar/__test__/Sidebar.test.tsx
frontend2/src/contexts/CurrentTeamContext.ts
frontend2/src/contexts/CurrentTeamProvider.tsx
frontend2/src/contexts/EpisodeProvider.tsx
frontend2/src/views/MyTeam.tsx

Clicking the leave team button should display the popup in the screenshot above. Clicking the cancel button should close the modal, and clicking the leave team button should leave the team. 
Clicking outside the modal should also close the modal.

Make leave team button work, add modal component

---

frontend2/src/components/EpisodeSwitcher.tsx
frontend2/src/components/Header.tsx
frontend2/src/contexts/EpisodeContext.ts
frontend2/src/contexts/EpisodeProvider.tsx
frontend2/src/utils/api/episode.ts
frontend2/src/views/Home.tsx

Adds Episode Switching to frontend!

Episode Switching

---

frontend2/src/App.tsx
frontend2/src/components/SectionCard.tsx
frontend2/src/components/sidebar/index.tsx
frontend2/src/components/tables/submissions/SubHistoryTable.tsx
frontend2/src/components/tables/submissions/TourneySubTable.tsx
frontend2/src/views/Submissions.tsx

create submission page w/ submission history and tourney submission history tables

Add submissions page

---

frontend2/src/App.tsx
frontend2/src/views/Account.tsx
frontend2/src/views/MyTeam.tsx

Add UI skeleton for user account page (only design, no functionality)

Add the user account settings page

---

backend/siarnaq/api/episodes/admin.py
frontend/src/views/getting-started.js
frontend/src/views/issues.js
frontend/src/views/multi-episode.jsx
frontend/src/views/queue.js
frontend/src/views/scrimmaging.js

Add scaffold link / name to frontend.
+ small update to client instructions in getting started
@ client please review the client instructions in getting started

prep for 2024 release

---

backend/siarnaq/api/compete/admin.py

Database protections should keep this safe.

Allow deleting matches

---

frontend2/src/App.tsx

With the staging backend
These links should work (and not redirect) when not logged in:
* http://localhost:3000/bc23/tournaments
* http://localhost:3000/bc23/
* http://localhost:3000/bc23/home
These links should redirect to the login page when not logged in:
* http://localhost:3000/bc23/team
* http://localhost:3000/account
These links should work when logged in
* http://localhost:3000/bc23/team
* http://localhost:3000/account
These links should display the not found component within the episode layout
* http://localhost:3000/bc23/nonexistent
These links should display the NotFound page (and not redirect)
* http://localhost:3000/nonexistent/nonexistent
* http://localhost:3000/nonexistent
* http://localhost:3000/nonexistent/nonexistent/nonexistent

Fix routing

---

backend/siarnaq/api/compete/test_views.py
backend/siarnaq/api/compete/views.py
frontend/src/components/scrimmageRequestForm.js

tested with reference player team in staging

only allow scrimmages against reference player (revert later)

---

docs-general/onboard.md
docs-general/operations.md
frontend2/docs/onboard.md

Resolves #63, resolves #681, resolves #546, resolves #527
Nathan read over like all of webinfra-related slack of all of fall and IAP 2024 and here is what came out.
This includes docs for releasing a game, among many others.

Add a ton of documentation of things we learned over IAP

---

frontend2/src/api/compete/useCompete.ts
frontend2/src/api/team/useTeam.ts
frontend2/src/components/tables/scrimmaging/RequestScrimModal.tsx
frontend2/src/views/Account.tsx
frontend2/src/views/JoinTeam.tsx
frontend2/src/views/MyTeam.tsx
frontend2/src/views/Register.tsx
frontend2/src/views/Submissions.tsx

Switches from mutateAsync to mutate as explained in the issue and slack. Closes #758 :rocket:

MutateAsync -> Mutate

---

frontend2/.eslintrc.js
frontend2/package.json
frontend2/src/App.tsx
frontend2/src/api/auth/authApi.ts
frontend2/src/api/loaders/passwordForgotLoader.ts
frontend2/src/api/user/useUser.ts
frontend2/src/api/user/userApi.ts
frontend2/src/api/user/userFactories.ts
frontend2/src/api/user/userKeys.ts
frontend2/src/views/PasswordChange.tsx
frontend2/src/views/PasswordForgot.tsx

Adds the "request" and "do" reset password pages! Resolves #793 :rocket:
Unfortunately, I am not sure how to test this in staging since the staging api doesn't seem to send password reset links... so maybe we just test this in prod? :shipit:

Password Reset

---

frontend2/src/api/team/useTeam.ts

Call onSuccess in useLeaveTeam after success

add call to onSuccess in useLeaveTeam

---

frontend2/src/api/user/useUser.ts

show specific registration errors

---

frontend2/src/api/auth/authApi.ts
frontend2/src/api/loaders/queueLoader.ts
frontend2/src/api/loaders/rankingsLoader.ts
frontend2/src/api/loaders/scrimmagingLoader.ts
frontend2/src/api/loaders/submissionsLoader.ts
frontend2/src/components/Header.tsx
frontend2/src/components/sidebar/SidebarSection.tsx
frontend2/src/components/sidebar/index.tsx
frontend2/src/views/Home.tsx

adds some checks to make sure that users can't access pages we don't want them to :sunglasses: 
* refactors sidebar logic, using an enum for each sidebar item to describe when it should be displayed

update sidebar for episode not released, add errors for episode released-only pages

---

frontend2/src/api/loaders/myTeamLoader.ts
frontend2/src/api/loaders/teamProfileLoader.ts
frontend2/src/components/EpisodeLayout.tsx
frontend2/src/components/SectionCard.tsx
frontend2/src/components/Table.tsx
frontend2/src/components/TableBottom.tsx
frontend2/src/components/compete/TournamentCountdown.tsx
frontend2/src/components/team/EligibilitySettings.tsx
frontend2/src/content/ManageContent.ts
frontend2/src/content/bc23.ts
frontend2/src/content/bc25.ts
frontend2/src/views/Account.tsx
frontend2/src/views/Home.tsx
frontend2/src/views/MyTeam.tsx
frontend2/src/views/QuickStart.tsx
frontend2/src/views/Resources.tsx
frontend2/src/views/Submissions.tsx
frontend2/src/views/TeamProfile.tsx
frontend2/src/views/Tournament.tsx
frontend2/src/views/Tournaments.tsx
frontend2/src/views/UserProfile.tsx

- Adds a loading prop to section card for nicer handling of loading data which its content depends on
- Adds some checks to certain pages so we redirect on data failure instead of blocking with an ugly loading interstitial
- Changes up our section card header to something that i think looks nicer (looking for feedback though)
- Adds preliminary content for bc25 (will need to create actual bc25java and bc25python episodes/content saturday?)
Closes #789  :rocket:

Prettier Loading

---

backend/siarnaq/api/compete/views.py
frontend/src/App.tsx
frontend/src/api/loaders/episodeLoader.ts
frontend/src/api/loaders/homeLoader.ts
frontend/src/api/loaders/tournamentLoader.ts
frontend/src/components/EpisodeLayout.tsx
frontend/src/components/tables/TournamentsTable.tsx
frontend/src/views/Account.tsx
frontend/src/views/Home.tsx
frontend/src/views/MyTeam.tsx
frontend/src/views/TeamProfile.tsx
frontend/src/views/UserProfile.tsx

so we dont run out of moneyyyyyyy

Disable rating history in frontend and backend so that we dont go broke

---

frontend/src/api/loaders/rankingsLoader.ts
frontend/src/components/sidebar/index.tsx
frontend/src/content/bc25java.ts
frontend/src/content/bc25python.ts
frontend/src/views/Home.tsx
frontend/src/views/MyTeam.tsx

- Add twitter to home page socials
- Add temporary "competition starts at ..." message to home page
- Correct lecture streaming info
- Reveal rankings page for non-released episodes
- Fix double scrimmaging record panel on "my_team" (lol)

Add small web niceties

---

frontend/src/components/EpisodeSwitcher.tsx
frontend/src/components/Header.tsx
frontend/src/views/CodeOfConduct.tsx

fixes mobile header and one link

fix mobile header

---

backend/siarnaq/api/episodes/models.py
saturn/Dockerfile
saturn/pkg/run/java.go
saturn/pkg/run/java8.go
saturn/pkg/run/python3.go
saturn/pkg/run/scaffold.go
saturn/pkg/saturn/task.go

- adds language options for java21
- adds ability for saturn runners to run matches with java21 and python3

Add python3 and java21 support on saturn

---

frontend/src/api/loaders/scrimmagingLoader.ts
frontend/src/api/loaders/submissionsLoader.ts
frontend/src/components/sidebar/index.tsx
frontend/src/views/Submissions.tsx

- Proper wording for submissions when viewing java/python episodes
- Allow staff teams to view submissions for unreleased episodes

Frontend submission fixes

---

frontend/src/components/sidebar/index.tsx
frontend/src/content/bc25java.ts
frontend/src/content/bc25python.ts
frontend/src/views/Resources.tsx

- pads sidebar y axis so all links are viewable on short screens
- fix team links
- fix hardcoded api/spec links

Fix team links and sidebar overflow

---

frontend/src/App.tsx
frontend/src/api/helpers.ts
frontend/src/components/MatchReplayButton.tsx
frontend/src/components/ResponsiveIframe.tsx
frontend/src/components/TableBottom.tsx
frontend/src/components/elements/Icon.tsx
frontend/src/components/elements/SelectMenu.tsx
frontend/src/components/sidebar/index.tsx
frontend/src/components/tables/QueueTable.tsx
frontend/src/components/tables/RankingsTable.tsx
frontend/src/components/tables/TournamentResultsTable.tsx
frontend/src/components/tables/TournamentsTable.tsx
frontend/src/components/tables/scrimmaging/InboxTable.tsx
frontend/src/components/tables/scrimmaging/OutboxTable.tsx
frontend/src/components/tables/scrimmaging/ScrimHistoryTable.tsx
frontend/src/components/tables/scrimmaging/TeamsTable.tsx
frontend/src/components/tables/scrimmaging/TournamentMatchesTable.tsx
frontend/src/components/tables/submissions/SubHistoryTable.tsx
frontend/src/views/Client.tsx
frontend/src/views/Submissions.tsx

Web Client

---

frontend/src/components/tables/TournamentsTable.tsx
frontend/src/content/bc25java.ts
frontend/src/content/bc25python.ts
frontend/src/utils/dateTime.ts
frontend/src/views/Client.tsx
frontend/src/views/Tournament.tsx

I LOOOOOOVE JAVASCRIPT DATES SOOOOOO MUCH!!!!!! :smile:

fix tournament times and change client dates

---

frontend/src/api/compete/competeKeys.ts

ahh emergency

---

backend/siarnaq/api/episodes/serializers.py
frontend/schema.yml
frontend/src/api/_autogen/models/Episode.ts
frontend/src/components/compete/chart/ChartBase.tsx
frontend/src/components/compete/chart/TeamChart.tsx
frontend/src/components/compete/chart/UserChart.tsx

- ending rating charts xAxis timeline by min(current_date, game_archive_date)

Chartbase end time

---

frontend/src/components/ResponsiveIframe.tsx
frontend/src/components/tables/scrimmaging/InboxTable.tsx
frontend/src/components/tables/scrimmaging/OutboxTable.tsx
frontend/src/views/Client.tsx

@TheApplePieGod can you review and if it looks good merge/release tyty :face_holding_back_tears:

fix client size and add scrim types

---

backend/siarnaq/api/teams/filters.py
backend/siarnaq/api/teams/views.py
frontend/schema.yml
frontend/src/api/_autogen/apis/TeamApi.ts
frontend/src/api/team/teamApi.ts
frontend/src/api/team/teamKeys.ts
frontend/src/api/team/useTeam.ts
frontend/src/components/Table.tsx
frontend/src/components/elements/Icon.tsx
frontend/src/components/elements/Pill.tsx
frontend/src/components/elements/SelectMultipleMenu.tsx
frontend/src/components/tables/RankingsTable.tsx
frontend/src/components/tables/scrimmaging/InboxTable.tsx
frontend/src/components/tables/scrimmaging/OutboxTable.tsx
frontend/src/components/tables/scrimmaging/TeamsTable.tsx
frontend/src/views/Rankings.tsx
frontend/src/views/Scrimmaging.tsx

filter rankings by eligibility! by popular demand!
adds lodash's uniqueId to prevent massive rendering issues :open_mouth:

filter rankings by eligibility

---

backend/siarnaq/api/episodes/admin.py
frontend/src/views/Submissions.tsx

- manual autoscrim action
- allow staff submissions when frozen
idk if allow subs thing works or not but if not we're gonna have to mess with gcloud stuff which is big sad :smiling_face_with_tear: 
closes #909

manual autoscrim and allow staff submissions when episode frozen

---

backend/siarnaq/api/teams/filters.py
frontend/src/views/Rankings.tsx

- change filter to be an AND
- fix duplication bug (which i think was on the api...)

Rankings filter by eligibility ANDed

---

backend/siarnaq/api/compete/serializers.py
backend/siarnaq/api/compete/test_views.py
backend/siarnaq/api/compete/views.py

- removes all unreleased tournament matches from the match queryset unless the user is staff
- TODO: test!

Hide Unreleased Tournament Matches

---

backend/siarnaq/api/episodes/admin.py
backend/siarnaq/api/episodes/models.py

allow manual autoscrims when episode frozen
